/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/appHeader.vue')['default']
    AppNavbar: typeof import('./components/appNavbar.vue')['default']
    CounterBaseCost: typeof import('./components/counterBaseCost.vue')['default']
    Dialog: typeof import('./components/dialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/ui/search.vue')['default']
    Table: typeof import('./components/table.vue')['default']
    TheCardPrice: typeof import('./components/theCardPrice.vue')['default']
    TheCardService: typeof import('./components/theCardService.vue')['default']
    TheCorporatesiteCalculation: typeof import('./components/calculation/theCorporatesiteCalculation.vue')['default']
    TheCounterBaseCost: typeof import('./components/theCounterBaseCost.vue')['default']
    TheDialog: typeof import('./components/theDialog.vue')['default']
    TheErrorComponent: typeof import('./components/theErrorComponent.vue')['default']
    TheErrorFooterAppbar: typeof import('./components/wireframes/footer/condition/theErrorFooterAppbar.vue')['default']
    TheErrorHeaderAppbar: typeof import('./components/wireframes/header/condition/theErrorHeaderAppbar.vue')['default']
    TheFooterAppbar: typeof import('./components/wireframes/footer/theFooterAppbar.vue')['default']
    TheHeaderAppbar: typeof import('./components/wireframes/header/theHeaderAppbar.vue')['default']
    TheLendingCalculation: typeof import('./components/calculation/theLendingCalculation.vue')['default']
    TheLoadingComponent: typeof import('./components/theLoadingComponent.vue')['default']
    TheLoadingFooterAppbar: typeof import('./components/wireframes/footer/condition/theLoadingFooterAppbar.vue')['default']
    TheLoadingHeaderAppbar: typeof import('./components/wireframes/header/condition/theLoadingHeaderAppbar.vue')['default']
    TheMultipageCalculation: typeof import('./components/calculation/theMultipageCalculation.vue')['default']
    TheOptions: typeof import('./components/theOptions.vue')['default']
    ThePromositeCalculation: typeof import('./components/calculation/thePromositeCalculation.vue')['default']
    TheSearch: typeof import('./components/ui/theSearch.vue')['default']
    TheShopCalculation: typeof import('./components/calculation/theShopCalculation.vue')['default']
    TheSiteCalculation: typeof import('./components/calculation/theSiteCalculation.vue')['default']
    TheToastError: typeof import('./components/condition/toasts/theToastError.vue')['default']
  }
}
